/**
 * All user-facing text lives here so the UI can be translated later.
 * Spanish is the default language.
 */
export const t = {
  appName: 'EasyPixel',
  untitled: 'sin título',

  menu: {
    file: 'Archivo',
    edit: 'Editar',
    sprite: 'Sprite',
    view: 'Ver',
    newSprite: 'Nuevo sprite…',
    open: 'Abrir…',
    save: 'Guardar',
    saveAs: 'Guardar como…',
    importPng: 'Importar PNG…',
    exportPng: 'Exportar PNG / GIF…',
    undo: 'Deshacer',
    redo: 'Rehacer',
    copy: 'Copiar',
    cut: 'Cortar',
    paste: 'Pegar',
    selectAll: 'Seleccionar todo',
    deselect: 'Quitar selección',
    deleteSelection: 'Borrar selección',
    clearCel: 'Limpiar capa en este frame',
    resize: 'Tamaño del lienzo…',
    flipH: 'Voltear horizontal',
    flipV: 'Voltear vertical',
    toggleGrid: 'Rejilla de píxeles',
    tileGrid: 'Rejilla de tiles',
    tileGridOff: 'sin rejilla',
    zoomIn: 'Acercar',
    zoomOut: 'Alejar',
    zoomFit: 'Ajustar a la ventana',
  },

  tools: {
    pencil: 'Lápiz',
    eraser: 'Borrador',
    bucket: 'Cubo de relleno',
    line: 'Línea',
    rect: 'Rectángulo',
    ellipse: 'Elipse',
    eyedropper: 'Cuentagotas',
    select: 'Selección',
    pan: 'Mano (mover vista)',
  },

  options: {
    brushSize: 'Tamaño',
    pixelPerfect: 'Pixel perfect',
    pixelPerfectHint: 'Elimina las esquinas dobles al dibujar trazos a mano',
    mirrorX: 'Espejo X',
    mirrorY: 'Espejo Y',
    contiguous: 'Contiguo',
    filled: 'Relleno',
    selectHint: 'Arrastra para seleccionar · arrastra dentro para mover · Intro para fijar · Esc para cancelar',
  },

  palette: {
    title: 'Paleta',
    primary: 'Color principal (clic izquierdo)',
    secondary: 'Color secundario (clic derecho)',
    swap: 'Intercambiar colores (X)',
    addColor: 'Añadir color principal a la paleta',
    removeColor: 'Quitar color seleccionado',
    editHint: 'Doble clic para editar un color',
    presets: 'Presets',
    importFile: 'Importar .gpl / .hex',
    exportFile: 'Exportar .hex',
    alpha: 'Alfa',
    replaceConfirm: '¿Reemplazar la paleta actual por «{name}»?',
    builtIn: 'Incluidas',
    mine: 'Mis paletas',
    more: 'Más opciones de paleta',
    saveToLibrary: 'Guardar en mis paletas…',
    saveTitle: 'Guardar paleta',
    saved: 'Paleta «{name}» guardada',
    lospec: 'Importar de Lospec…',
    lospecTitle: 'Importar paleta de Lospec',
    lospecHint: 'Nombre o enlace de la paleta en lospec.com/palette-list (p. ej. «resurrect-64», «apollo»).',
    lospecSearch: 'Buscar',
    lospecApply: 'Usar en el sprite',
    lospecSave: 'Guardar también en mis paletas',
    deleteSaved: 'Borrar «{name}»',
    deleteConfirm: '¿Borrar la paleta «{name}» de tus paletas?',
  },

  layers: {
    title: 'Capas',
    add: 'Nueva capa',
    duplicate: 'Duplicar capa',
    remove: 'Eliminar capa',
    up: 'Subir capa',
    down: 'Bajar capa',
    merge: 'Combinar con la de abajo',
    visible: 'Mostrar / ocultar',
    lock: 'Bloquear / desbloquear',
    opacity: 'Opacidad',
    rename: 'Doble clic para renombrar',
  },

  frames: {
    title: 'Frames',
    add: 'Nuevo frame',
    duplicate: 'Duplicar frame',
    remove: 'Eliminar frame',
    left: 'Mover a la izquierda',
    right: 'Mover a la derecha',
    duration: 'Duración (ms)',
    prev: 'Frame anterior (,)',
    next: 'Frame siguiente (.)',
  },

  animation: {
    title: 'Animaciones',
    newTag: 'Nueva animación',
    newTagHint: 'Crea una animación con los frames seleccionados (Mayús+clic para elegir un rango)',
    editTag: 'Editar animación',
    allFrames: 'Todos los frames',
    direction: 'Dirección',
    forward: 'Adelante',
    reverse: 'Atrás',
    pingpong: 'Ping-pong',
    loop: 'Bucle',
    from: 'Desde frame',
    to: 'Hasta frame',
    remove: 'Eliminar animación',
    removeConfirm: '¿Eliminar la animación «{name}»? Los frames no se borran.',
    onionSkin: 'Papel cebolla',
    onionHint: 'Muestra los frames vecinos: rojo = anterior, azul = siguiente',
    preview: 'Vista previa',
    play: 'Reproducir (P)',
    pause: 'Pausa (P)',
    sheet: 'Hoja',
    anim: 'Animación',
    scale: 'Escala',
    fit: 'Ajustar',
    fps: '{fps} fps · {ms} ms',
    nameExists: 'Ya existe una animación con ese nombre',
    nameHint: 'Usa nombres como idle, walk, run, jump, attack… (se usarán en Godot)',
  },

  reference: {
    title: 'Referencia',
    load: 'Imagen de referencia…',
    replace: 'Cambiar imagen',
    remove: 'Quitar referencia',
    zoom: 'Tamaño',
    above: 'Mostrar encima (para calcar)',
  },

  godot: {
    menuExport: 'Exportar a Godot…',
    menuReexport: 'Re-exportar a Godot',
    title: 'Exportar a Godot 4',
    folder: 'Carpeta destino (dentro de tu proyecto Godot)',
    choose: 'Elegir…',
    detected: 'Proyecto Godot: {root}',
    resPath: 'Ruta en Godot: {res}',
    notProject: 'No se encontró project.godot en esta carpeta ni en sus padres.',
    browserNote:
      'En la versión de navegador los archivos se descargan: colócalos en la raíz de tu proyecto Godot (res://).',
    columns: 'Columnas',
    spacing: 'Separación',
    scale: 'Escala',
    autoplay: 'Animación inicial',
    remember: 'Recordar estos ajustes en el sprite',
    files: 'Se generarán:',
    pngHint: 'spritesheet ({w}×{h} px, hframes={h1}, vframes={v1})',
    tresHint: 'SpriteFrames con {n} animación(es): {names}',
    tscnHint: 'escena AnimatedSprite2D lista para arrastrar (filtro Nearest, autoplay)',
    noTagsHint: 'Sin animaciones definidas: se exportará una animación «default» con todos los frames.',
    exported: 'Exportado a Godot: {res} ({n} archivos)',
    pingpongHint: 'Las animaciones ping-pong y en reversa se expanden (Godot solo reproduce hacia delante).',
    modeSprite: 'Sprite animado',
    modeTileset: 'TileSet',
    tileWidth: 'Ancho de tile',
    tileHeight: 'Alto de tile',
    tileMismatch: 'El lienzo ({w}×{h}) debe ser múltiplo del tamaño de tile.',
    tilesPngHint: 'atlas de tiles ({w}×{h} px, primer frame con todas las capas visibles)',
    tilesetHint: 'TileSet con un atlas de {c}×{r} celdas (solo se registran los tiles con píxeles)',
    tilesetUsage: 'En Godot: añade un TileMapLayer, asígnale este TileSet y pinta.',
    exportedTiles: 'TileSet exportado a {res} ({n} tiles)',
  },

  tabs: {
    close: 'Cerrar (clic central)',
  },

  mcp: {
    createdByClaude: 'creado por Claude',
    connectTitle: 'Conectar con Claude (MCP)',
    menuConnect: 'Conectar con Claude…',
    listening: 'MCP activo en {url}',
    stopped: 'MCP detenido',
    error: 'MCP no disponible: {error}',
    webOnly: 'El servidor MCP solo funciona en la app de escritorio.',
    working: 'Claude: {tool}',
    intro:
      'EasyPixel incluye un servidor MCP local. Conecta Claude y pídele que dibuje: verás los cambios en directo y podrás deshacerlos con Ctrl+Z.',
    claudeCode: 'Claude Code',
    claudeCodeHint: 'Ejecuta este comando en una terminal (una sola vez):',
    claudeDesktop: 'Claude Desktop',
    claudeDesktopHint:
      'Añade esto a claude_desktop_config.json (Ajustes → Desarrollador → Editar configuración) y reinicia Claude Desktop:',
    copy: 'Copiar',
    copied: 'Copiado al portapapeles',
    tryPrompt: 'Prueba a pedirle:',
    examplePrompt:
      'Dibuja en EasyPixel un caballero de 32×32 con paleta Endesga 32 y crea una animación idle de 4 frames.',
    keepOpen: 'EasyPixel debe estar abierto mientras Claude dibuja.',
  },

  dialogs: {
    cancel: 'Cancelar',
    ok: 'Aceptar',
    create: 'Crear',
    name: 'Nombre',
    width: 'Ancho',
    height: 'Alto',
    size: 'Tamaño',
    palette: 'Paleta',
    newTitle: 'Nuevo sprite',
    resizeTitle: 'Tamaño del lienzo',
    anchor: 'Anclaje',
    importTitle: 'Importar PNG',
    importAsNew: 'Nuevo sprite',
    importAsNewHint: 'Crea un sprite nuevo. Si es una spritesheet, indica el tamaño de cada frame para cortarla.',
    importIntoLayer: 'Pegar en la capa actual',
    importIntoLayerHint: 'Se pega como selección flotante; muévela y pulsa Intro para fijarla.',
    frameSize: 'Tamaño de frame',
    spacing: 'Separación',
    margin: 'Margen',
    skipEmpty: 'Ignorar frames vacíos',
    usePaletteFromImage: 'Crear paleta con los colores de la imagen',
    framesDetected: '{n} frame(s)',
    exportTitle: 'Exportar imagen',
    exportCurrent: 'Frame actual',
    exportSheet: 'Spritesheet (todos los frames)',
    exportGif: 'GIF animado',
    columns: 'Columnas',
    scale: 'Escala',
    resultSize: 'Resultado: {w}×{h} px',
    export: 'Exportar',
    discardChanges: 'Hay cambios sin guardar. ¿Continuar y descartarlos?',
  },

  status: {
    saved: 'Guardado en {path}',
    opened: 'Abierto {name}',
    exported: 'Exportado {path}',
    copied: 'Copiado',
    noSelection: 'No hay selección',
    nothingToPaste: 'El portapapeles está vacío',
  },
} as const;

export function fmt(template: string, values: Record<string, string | number>): string {
  return template.replace(/\{(\w+)\}/g, (_, k: string) => String(values[k] ?? `{${k}}`));
}
